67-stop_me_if_you_can

diff --git a/0x05-processes_and_signals/8-beheaded_process b/0x05-processes_and_signals/8-beheaded_process
--- a/0x05-processes_and_signals/8-beheaded_process
+++ b/0x05-processes_and_signals/8-beheaded_process
@@ -2,3 +2,9 @@
 # script that stops a process without using kill
 
 pkill -f "7-highlander"
+
+if [[ $? -eq 0 ]]; then
+	echo "script terminated"
+else
+	echo "could not be terminated"
+fi
